### PR TITLE
Refactored the Ruby variant

### PR DESCRIPTION
**Pull request by mhutter**
- implemented the code object oriented
- moved core extensions into refinements
- colored the output :-)
- added some minimalist documentation

### CODE REVIEW

**Comment by dbrgn** [comment]
Thanks for the improvements. A lot of the things make sense, but is the code actually simpler to read for a beginner?

The goal of these scripts are to bring across the concepts of a perceptron and its implementation to someone new to them. I'm not sure fully modularized and flexible code fulfils that goal.

What do you think? (You may disagree of course :))

**Comment by mhutter** [comment]
Hmm yes you have a point...

The main issue I have with my original code is that it extends core classes. This is very handy but also really dangerous, especially for beginners.

I have a few ideas for improvements, I'll update the PR later.

**Comment by dbrgn** [comment]
Maybe if you include things like `refine` but get rid of the class? :) People can always wrap something in a class or use a full-featured perceptron library for production.

**Comment by mhutter** [comment]
I cut out all the unneccessary stuff, should be easier to read now!

**Comment by dbrgn** [comment]
Great!

**Pull request merged**
